export const QUERY_CREATE_REQUEST = 'QUERY_CREATE_REQUEST'
export const QUERY_CREATE_SUCCESS = 'QUERY_CREATE_SUCCESS'
export const QUERY_CREATE_FAIL = 'QUERY_CREATE_FAIL'
export const QUERY_CREATE_RESET = 'QUERY_CREATE_RESET'

export const QUERY_LIST_REQUEST = 'QUERY_LIST_REQUEST'
export const QUERY_LIST_SUCCESS = 'QUERY_LIST_SUCCESS'
export const QUERY_LIST_FAIL = 'QUERY_LIST_FAIL'

export const QUERY_DETAILS_REQUEST = 'QUERY_DETAILS_REQUEST'
export const QUERY_DETAILS_SUCCESS = 'QUERY_DETAILS_SUCCESS'
export const QUERY_DETAILS_FAIL = 'QUERY_DETAILS_FAIL'

export const QUERY_DELETE_REQUEST = 'QUERY_DELETE_REQUEST'
export const QUERY_DELETE_SUCCESS = 'QUERY_DELETE_SUCCESS'
export const QUERY_DELETE_FAIL = 'QUERY_DELETE_FAIL'