export const SESSION_DETAIL_REQUEST = "SESSION_DETAIL_REQUEST";
export const SESSION_DETAIL_SUCCESS = "SESSION_DETAIL_SUCCESS";
export const SESSION_DETAIL_FAIL = "SESSION_DETAIL_FAIL";

export const SESSION_CREATE_REQUEST = "SESSION_CREATE_REQUEST";
export const SESSION_CREATE_SUCCESS = "SESSION_CREATE_SUCCESS";
export const SESSION_CREATE_FAIL = "SESSION_CREATE_FAIL";

export const SESSION_UPDATE_REQUEST = "SESSION_UPDATE_REQUEST";
export const SESSION_UPDATE_SUCCESS = "SESSION_UPDATE_SUCCESS";
export const SESSION_UPDATE_FAIL = "SESSION_UPDATE_FAIL";
