export const STUDENT_DETAIL_REQUEST = 'STUDENT_DETAIL_REQUEST'
export const STUDENT_DETAIL_SUCCESS = 'STUDENT_DETAIL_SUCCESS'
export const STUDENT_DETAIL_FAIL = 'STUDENT_DETAIL_FAIL'

export const STUDENT_DETAIL_USER_POPULATE_REQUEST = 'STUDENT_DETAIL_USER_POPULATE_REQUEST'
export const STUDENT_DETAIL_USER_POPULATE_SUCCESS = 'STUDENT_DETAIL_USER_POPULATE_SUCCESS'
export const STUDENT_DETAIL_USER_POPULATE_FAIL = 'STUDENT_DETAIL_USER_POPULATE_FAIL'

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'

