export const TEACHER_LIST_REQUEST = "TEACHER_LIST_REQUEST";
export const TEACHER_LIST_SUCCESS = "TEACHER_LIST_SUCCESS";
export const TEACHER_LIST_FAIL = "TEACHER_LIST_FAIL";

export const TEACHER_DETAIL_REQUEST = "TEACHER_DETAIL_REQUEST";
export const TEACHER_DETAIL_SUCCESS = "TEACHER_DETAIL_SUCCESS";
export const TEACHER_DETAIL_FAIL = "TEACHER_DETAIL_FAIL";

export const TEACHER_UPDATE_REQUEST = "TEACHER_UPDATE_REQUEST";
export const TEACHER_UPDATE_SUCCESS = "TEACHER_UPDATE_SUCCESS";
export const TEACHER_UPDATE_FAIL = "TEACHER_UPDATE_FAIL";

export const TEACHER_UPDATE_CREDIT_REQUEST = "TEACHER_UPDATE_CREDIT_REQUEST";
export const TEACHER_UPDATE_CREDIT_SUCCESS = "TEACHER_UPDATE_CREDIT_SUCCESS";
export const TEACHER_UPDATE_CREDIT_FAIL = "TEACHER_UPDATE_CREDIT_FAIL";
